ALTER TABLE trait ADD COLUMN position_x INTEGER DEFAULT NULL;
ALTER TABLE trait ADD COLUMN position_y INTEGER DEFAULT NULL;

ALTER TABLE trait ADD COLUMN specialization INTEGER DEFAULT NULL;
ALTER TABLE trait ADD COLUMN specialization_position_x INTEGER DEFAULT NULL;
ALTER TABLE trait ADD COLUMN specialization_position_y INTEGER DEFAULT NULL;